/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arbolE;

import java.awt.Color;
import java.awt.Desktop;
import java.io.*;
import java.util.Vector;
import javax.sound.sampled.*;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aneao
 */
public class Frameinterfaz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Frameinterfaz.class.getName());
    private static final java.util.Set<String> OPERADORES = java.util.Set.of("+", "-", "*", "/");
    String nPolaca;
    ArbolAgenteIA arbol;
    int temp;
    Nodo arbolExpresion;
    FrameCuadruplos Cuadruplas;
    FrameTripletas frameTripletas;
    
    String izq, der;
    String emuLocal;
    int Contador;
    
    /**
     * Creates new form Frameinterfaz
     */
    public Frameinterfaz() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        emuLocal = "";
        izq = der = "";
        temp = Contador = 0;
    }
    
    // Métodos inOrden, postOrden y preOrden 9-Julio
    public void inOrden(Nodo n){
        if (n!= null){
            inOrden(n.getIzquierdo());
            jTxtInOrden.append(n.getDato()+"\n");
            inOrden(n.getDerecho());
            //15 julio
            
            
            switch (n.getDato()) {
                case "+": System.out.println("add"); 
                            izq = n.getIzquierdo().getDato();
                            der = n.getDerecho().getDato(); 
                            
                            System.out.println("izq: "+izq);
                            System.out.println("der: "+der);
                            emuLocal += "mov ax, "+n.getIzquierdo().getDato()+"\n";
                            emuLocal += "mov bx, "+n.getDerecho().getDato()+"\n";
                            emuLocal += "add ax,bx\n\n";
                            break;
                case "-": System.out.println("sub"); 
                            izq = n.getIzquierdo().getDato();
                            der = n.getDerecho().getDato(); break;
                case "/": System.out.println("div"); 
                            izq = n.getIzquierdo().getDato();
                            der = n.getDerecho().getDato(); break;
                case "*": System.out.println("mul"); 
                            izq = n.getIzquierdo().getDato();
                            der = n.getDerecho().getDato(); break;
            }// fin switch
        }// if
    }// inOrden
    
    public void preOrden(Nodo n){
        if(n!=null){
            jTxtPreOrden.append(n.getDato()+"\n");
            nPolaca+=jNotacionPolaca.getText()+n.getDato()+" ";
            jNotacionPolaca.setText(jNotacionPolaca.getText()+n.getDato()+" ");
            preOrden(n.getIzquierdo());
            preOrden(n.getDerecho());
        } // if
    }// preOrden
    
    public void postOrden(Nodo n){
        if (n!=null){
            postOrden(n.getIzquierdo());
            postOrden(n.getDerecho());
            jTxtPostOrden.append(n.getDato()+"\n");
        }// if
    }// postOrden
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabla_Simbolos = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblSimbolos = new javax.swing.JTable();
        frLeerASM = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        imagenRedondeada4 = new Componentes.ImagenRedondeada();
        imagenRedondeada5 = new Componentes.ImagenRedondeada();
        imagenRedondeada6 = new Componentes.ImagenRedondeada();
        jPanel7 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnSalirASM = new javax.swing.JButton();
        btnAbrirASM = new javax.swing.JButton();
        btnLimpiarASM = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        imagenRedondeada1 = new Componentes.ImagenRedondeada();
        imagenRedondeada2 = new Componentes.ImagenRedondeada();
        imagenRedondeada3 = new Componentes.ImagenRedondeada();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtPreOrden = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtPostOrden = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxtInOrden = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTxtReglasEjecutadas = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTxtCodigo3Direcciones = new javax.swing.JTextArea();
        BtnAgente = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jNotacionPolaca = new javax.swing.JTextField();
        btnClean = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        Tabla_Simbolos.setMinimumSize(new java.awt.Dimension(400, 400));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tabla de Símbolos");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        tblSimbolos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblSimbolos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Token / id", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSimbolos.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        tblSimbolos.setMinimumSize(new java.awt.Dimension(30, 30));
        tblSimbolos.setPreferredSize(new java.awt.Dimension(150, 100));
        jScrollPane6.setViewportView(tblSimbolos);

        javax.swing.GroupLayout Tabla_SimbolosLayout = new javax.swing.GroupLayout(Tabla_Simbolos.getContentPane());
        Tabla_Simbolos.getContentPane().setLayout(Tabla_SimbolosLayout);
        Tabla_SimbolosLayout.setHorizontalGroup(
            Tabla_SimbolosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tabla_SimbolosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Tabla_SimbolosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Tabla_SimbolosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        Tabla_SimbolosLayout.setVerticalGroup(
            Tabla_SimbolosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tabla_SimbolosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        frLeerASM.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Archivo ASM");

        imagenRedondeada4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ITTepic_logo.jpg"))); // NOI18N

        imagenRedondeada5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/PatoOla.jpeg"))); // NOI18N

        imagenRedondeada6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/yo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenRedondeada4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagenRedondeada5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagenRedondeada6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenRedondeada4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagenRedondeada5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(imagenRedondeada6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane7.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nombre del Archivo");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalirASM.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnSalirASM.setText("Salir");
        btnSalirASM.addActionListener(this::btnSalirASMActionPerformed);

        btnAbrirASM.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnAbrirASM.setText("Abrir");
        btnAbrirASM.addActionListener(this::btnAbrirASMActionPerformed);

        btnLimpiarASM.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnLimpiarASM.setText("Limpiar");
        btnLimpiarASM.addActionListener(this::btnLimpiarASMActionPerformed);

        javax.swing.GroupLayout frLeerASMLayout = new javax.swing.GroupLayout(frLeerASM.getContentPane());
        frLeerASM.getContentPane().setLayout(frLeerASMLayout);
        frLeerASMLayout.setHorizontalGroup(
            frLeerASMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frLeerASMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frLeerASMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frLeerASMLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiarASM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAbrirASM)
                .addGap(18, 18, 18)
                .addComponent(btnSalirASM)
                .addGap(14, 14, 14))
        );
        frLeerASMLayout.setVerticalGroup(
            frLeerASMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frLeerASMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frLeerASMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalirASM)
                    .addComponent(btnAbrirASM)
                    .addComponent(btnLimpiarASM))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Árbol de expresiones");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Árbol de expresiones - LyA2");

        imagenRedondeada1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ITTepic_logo.jpg"))); // NOI18N

        imagenRedondeada2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/PatoOla.jpeg"))); // NOI18N

        imagenRedondeada3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/yo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenRedondeada1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagenRedondeada2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagenRedondeada3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenRedondeada1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagenRedondeada2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(imagenRedondeada3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTextField1.setBackground(new java.awt.Color(204, 255, 153));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("Expresión");

        jTxtPreOrden.setColumns(20);
        jTxtPreOrden.setRows(5);
        jScrollPane1.setViewportView(jTxtPreOrden);

        jTxtPostOrden.setColumns(20);
        jTxtPostOrden.setRows(5);
        jScrollPane2.setViewportView(jTxtPostOrden);

        jTxtInOrden.setColumns(20);
        jTxtInOrden.setRows(5);
        jScrollPane3.setViewportView(jTxtInOrden);

        jTxtReglasEjecutadas.setColumns(20);
        jTxtReglasEjecutadas.setRows(5);
        jScrollPane4.setViewportView(jTxtReglasEjecutadas);

        jTxtCodigo3Direcciones.setColumns(20);
        jTxtCodigo3Direcciones.setRows(5);
        jScrollPane5.setViewportView(jTxtCodigo3Direcciones);

        BtnAgente.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        BtnAgente.setText("AgenteIA");
        BtnAgente.addActionListener(this::BtnAgenteActionPerformed);

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton3.setText("Optimiza Inter ...");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton7.setText("Compila");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addGap(80, 80, 80))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAgente)
                    .addComponent(jButton3)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Notación Polaca");

        jNotacionPolaca.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jNotacionPolaca.addActionListener(this::jNotacionPolacaActionPerformed);

        btnClean.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnClean.setText("Clean");
        btnClean.addActionListener(this::btnCleanActionPerformed);

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton4.setText("Código de 3 direcciones");
        jButton4.setActionCommand("Codigo de 3 direcciones");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton5.setText("Tabla de símbolos");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNotacionPolaca, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(btnClean)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNotacionPolaca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClean)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(251, 186, 7));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pre Orden");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("In Orden");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Post Orden");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Reglas Semánticas");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Código 3 direcciones");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton6.setText("Direcciones");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton2.setText("Cuadruplos");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton8.setText("ASM");
        jButton8.addActionListener(this::jButton8ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(566, 566, 566)
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton2)
                    .addComponent(jButton8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Cuadruplas = new FrameCuadruplos(arbolExpresion);
        Cuadruplas.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jNotacionPolacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNotacionPolacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNotacionPolacaActionPerformed

    private void BtnAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgenteActionPerformed
        jTxtReglasEjecutadas.setText(""); jTxtCodigo3Direcciones.setText("");
        jTxtInOrden.setText(""); jTxtPreOrden.setText(""); jTxtPostOrden.setText("");
        temp=0;
        
        String datos="";
        arbol = new ArbolAgenteIA();
        datos = jTextField1.getText();
        arbolExpresion = arbol.crear(datos); //Enviar los datos al árbol = expresión
        jTxtReglasEjecutadas.append(arbol.getReglasEjecutadas());
        archivoReglasEjecutadas(arbol.getReglasEjecutadas());
        
        preOrden(arbolExpresion);
        inOrden(arbolExpresion);
        postOrden(arbolExpresion);
        //intermedio(arbolExpresion);
        intermedioOptimizado(arbolExpresion);
        
        arbol.emu86 += ".code \n"+
                        "mov ax,@data \n"+
                        "mov ds,ax \n";
        String finalEmu = arbol.emu86+this.emuLocal;
        finalEmu += "\n mov ax,4c00h \n"+
                "int 21h \n end";
        showMessageDialog(null,finalEmu); // 15 julio   
        Contador++;
        generaEmutasm(finalEmu, Contador);
        sonido();
        
        PersonalizarPanelArbol p = new PersonalizarPanelArbol();
        p.setModal(true);
        p.setLocationRelativeTo(null);
        p.setVisible(true);
        
        JFrame ventana = new JFrame("Visualizador de Árboles - LyA2");
        PanelArbol panel = new PanelArbol(arbolExpresion, p);
        
        ventana.add(panel);
        ventana.setSize(600,400);
        ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        
        JFrame ventana2 = new JFrame("Visualizador de GDA - LyA2");
        PanelGrafo panel2 = new PanelGrafo(arbol.convertirAGAD(arbolExpresion), panel.getColorNodo(), panel.getAnchoNodo()/2, panel.getColorLinea(), panel.getAnchoLinea());
              
        ventana2.add(panel2);
        ventana2.setSize(600,400);
        ventana2.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventana2.setLocationRelativeTo(null);
        ventana2.setVisible(true);
        
        jTxtCodigo3Direcciones.append(arbolExpresion.getCodigoIntermedio());
        
        frameTripletas = new FrameTripletas(arbol.getTripletas());
        frameTripletas.setVisible(true);
    }//GEN-LAST:event_BtnAgenteActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
        jTxtReglasEjecutadas.setText(""); 
    }//GEN-LAST:event_btnCleanActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTxtCodigo3Direcciones.setText("");
        //jTxtCodigo3Direcciones.append(codigoI);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel m = (DefaultTableModel) tblSimbolos.getModel();
            m.setRowCount(0);
            System.out.println("tabla");
            arbol.tablaSimbolos.forEach((clave,valor)->{
                Vector simbolo = new Vector();
                simbolo.add(clave); simbolo.add(valor);
                m.addRow(simbolo);
                System.out.println(simbolo.toString());
            });

            Tabla_Simbolos.setModal(true);
            Tabla_Simbolos.setLocationRelativeTo(null);
            Tabla_Simbolos.setVisible(true);
        } catch (Exception e) {
            showMessageDialog(null, "Compila una expresión primero");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Tabla_Simbolos.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        File archivoMP4 = new File("Optimizacion.mp4");

        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().open(archivoMP4);
            } catch (IOException e) {
                System.out.println("No se pudo abrir el archivo: " + e.getMessage());
            }
        }
        
        showMessageDialog(null,"Optimización implemetada correctamente");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        FrameDescripcion ventanaIntermedio = new FrameDescripcion();
        ventanaIntermedio.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnSalirASMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirASMActionPerformed
        // TODO add your handling code here:
        frLeerASM.dispose();
    }//GEN-LAST:event_btnSalirASMActionPerformed

    private void btnAbrirASMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirASMActionPerformed
        // TODO add your handling code here:
        leerArchivoAsm(jTextField2.getText());
    }//GEN-LAST:event_btnAbrirASMActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        frLeerASM.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnLimpiarASMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarASMActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_btnLimpiarASMActionPerformed
    
    public void archivoReglasEjecutadas (String reglasEjecutadas){
        String rutaArchivo = "reglasSemanticas.txt";

        // Uso de try-with-resources para cerrar automáticamente el archivo
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(rutaArchivo))) {
            bw.write(reglasEjecutadas);
            System.out.println("Archivo creado y guardado exitosamente.");
        } catch (IOException e) {
            System.out.println("Ocurrió un error al guardar el archivo:");
            e.printStackTrace();
        }
    }
    
    public void intermedio(Nodo n){
        if (n!=null){
            intermedio(n.getIzquierdo());
            intermedio(n.getDerecho());
            if(n.getIzquierdo()==null && n.getDerecho()==null){
                n.setLugar(n.getDato()+" ");
                n.setCodigoIntermedio("");
            }else{
                if(n.getDato().equals("+")||n.getDato().equals("*")||n.getDato().equals("/")||n.getDato().equals("-")){
                    temp++;
                    n.setLugar("T"+temp);
                    Nodo izquierdo = n.getIzquierdo();
                    Nodo derecho = n.getDerecho();
                    String codigoI = "";
                    codigoI = izquierdo.getCodigoIntermedio()+" "+derecho.getCodigoIntermedio()+" "+n.getLugar()+" = "+izquierdo.getLugar()
                            +" "+n.getDato()+" "+derecho.getLugar();
                    n.setCodigoIntermedio(codigoI+"\n");
                    
                }else{
                    if (n.getDato().equals("=")){
                        String codigoI = "";
                        Nodo izquierdo = n.getIzquierdo();
                        Nodo derecho = n.getDerecho();
                        codigoI = derecho.getDato()+" "+izquierdo.getLugar()+" = T"+temp+"\n";
                        n.setCodigoIntermedio(codigoI);
                    }//equals =
                } // equals +-/*
            }// getDerecho getIzquierdo
        }// n!=null
    }//intermedio
    
    public void intermedioOptimizado(Nodo n) {
        if (n == null) return;

        Nodo izquierdo = n.getIzquierdo();
        Nodo derecho = n.getDerecho();

        intermedio(izquierdo);
        intermedio(derecho);

        if (izquierdo == null && derecho == null) {
            n.setLugar(n.getDato() + " ");
            n.setCodigoIntermedio("");
            return;
        }

        if (OPERADORES.contains(n.getDato())) {
            temp++;
            n.setLugar("T" + temp);
            String codigoI = izquierdo.getCodigoIntermedio() + " " + derecho.getCodigoIntermedio()
                    + " " + n.getLugar() + " = " + izquierdo.getLugar() + " " + n.getDato() + " " + derecho.getLugar();
            n.setCodigoIntermedio(codigoI + "\n");
            return;
        }

        if (n.getDato().equals("=")) {
            // Arrastro el código del hijo derecho, si no, se pierde la subexpresión
            String codigoI = derecho.getCodigoIntermedio()
                    + izquierdo.getLugar() + " = T" + temp + "\n";
            n.setCodigoIntermedio(codigoI);
        }
    }
    
    public void generaEmutasm(String emu, int i){
        try{
            FileWriter escritor = new FileWriter("e"+i+".asm");
            escritor.write(emu);
            escritor.close();
            System.out.println("Archivo creado exitosamente");
        }
        catch(Exception e){
            System.out.println("Ha ocurrido un error al crear el archivo");
        }
    }// generaEmutasm
    
    public void sonido(){
        //sonido
        try {
            File sonido = new File("src/arbolE/sonido.wav");
            if (sonido.exists()) {
                AudioInputStream audioStream = AudioSystem.getAudioInputStream(sonido);
                Clip clip = AudioSystem.getClip();
                clip.open(audioStream);
                clip.start(); 
            } else {
                showMessageDialog(null, "No se encontró el archivo de sonido.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            showMessageDialog(null, "Error al reproducir el sonido.");
        }
    }
    
    public void leerArchivoAsm(String archivo) {
        
        File archivoASM = new File(archivo+".asm");

        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().open(archivoASM);
            } catch (IOException e) {
                System.out.println("No se pudo abrir el archivo: " + e.getMessage());
            }
        }
        
        try (BufferedReader br = new BufferedReader(new FileReader(archivoASM))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                jTextArea1.append(linea+"\n");
            }
        } catch (IOException e) {
            System.err.println("Error al leer el archivo: " + e.getMessage());
        }
        
        showMessageDialog(null,"Archivo leído correctamente");
    }
    
    public Nodo getArbolExpresion() {
        return arbolExpresion;
    }

    public void setArbolExpresion(Nodo arbolExpresion) {
        this.arbolExpresion = arbolExpresion;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Frameinterfaz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgente;
    private javax.swing.JDialog Tabla_Simbolos;
    private javax.swing.JButton btnAbrirASM;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnLimpiarASM;
    private javax.swing.JButton btnSalirASM;
    private javax.swing.JFrame frLeerASM;
    private Componentes.ImagenRedondeada imagenRedondeada1;
    private Componentes.ImagenRedondeada imagenRedondeada2;
    private Componentes.ImagenRedondeada imagenRedondeada3;
    private Componentes.ImagenRedondeada imagenRedondeada4;
    private Componentes.ImagenRedondeada imagenRedondeada5;
    private Componentes.ImagenRedondeada imagenRedondeada6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNotacionPolaca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextArea jTxtCodigo3Direcciones;
    private javax.swing.JTextArea jTxtInOrden;
    private javax.swing.JTextArea jTxtPostOrden;
    private javax.swing.JTextArea jTxtPreOrden;
    private javax.swing.JTextArea jTxtReglasEjecutadas;
    private javax.swing.JTable tblSimbolos;
    // End of variables declaration//GEN-END:variables
}
